//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_net {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Calendar calendar1;
		
		protected System.Web.UI.WebControls.WebParts.EditorZone editZone1;
	}
}
